version: "3"

services:
    mipostgresql:   # Nombre resoluble a traves de DNS para conectarme con el contenedor
        container_name: maestro     # Nombre del contenedor. Útil para lanzar comandos de docker
                                        # Arrancarlo, pararlo, ver los logs, borrarlo
        image:  postgres:14.2
        ports:
            - 5432:5432
        restart: unless-stopped     # Configurar el postgresql como un servicio con arranque automatico con la maquina
        environment:
            - POSTGRES_PASSWORD=password 
            - POSTGRES_USER=usuario
            - POSTGRES_DB=curso
        volumes:
            # Que datos que genera el contenedor realmente se guarden en una carpeta del HOST
            - /home/ubuntu/environment/datos/postgres:/var/lib/postgresql/data
            # Inyectar ficheros del host al contenedor
            - /home/ubuntu/environment/curso/instalacion/postgresql.conf:/etc/postgresql/postgresql.conf
            - /home/ubuntu/environment/curso/instalacion/pg_hba.conf:/etc/postgresql/pg_hba.conf
            
    replicasql:   # Nombre resoluble a traves de DNS para conectarme con el contenedor
        container_name: replica     # Nombre del contenedor. Útil para lanzar comandos de docker
                                        # Arrancarlo, pararlo, ver los logs, borrarlo
        image:  postgres:14.2
        ports:
            - 5433:5432
        restart: unless-stopped     # Configurar el postgresql como un servicio con arranque automatico con la maquina
        environment:
            - POSTGRES_PASSWORD=password 
            - POSTGRES_USER=usuario
            - POSTGRES_DB=curso
        volumes:
            # Que datos que genera el contenedor realmente se guarden en una carpeta del HOST
            - /home/ubuntu/environment/datos/backup:/var/lib/postgresql/data
            # Inyectar ficheros del host al contenedor
            - /home/ubuntu/environment/curso/instalacion/postgresql.conf:/etc/postgresql/postgresql.conf
            - /home/ubuntu/environment/curso/instalacion/pg_hba.conf:/etc/postgresql/pg_hba.conf
